import {
  defineConfig,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'
import presetTheme from 'unocss-preset-theme'

export default defineConfig({
  shortcuts: [
  ],
  theme: {
    colors: {
      'primary': '#673ab7',
      'success': '#22c55e',
      'warning': '#eab308',
      'surface-tint': '#68548E',
      'on-primary': '#FFFFFF',
      'primary-container': '#EBDDFF',
      'on-primary-container': '#230F46',
      'secondary': '#635B70',
      'on-secondary': '#FFFFFF',
      'secondary-container': '#E9DEF8',
      'on-secondary-container': '#1F182B',
      'tertiary': '#7E525D',
      'on-tertiary': '#FFFFFF',
      'tertiary-container': '#FFD9E1',
      'on-tertiary-container': '#31101B',
      'error': '#BA1A1A',
      'on-error': '#FFFFFF',
      'error-container': '#FFDAD6',
      'on-error-container': '#410002',
      'background': '#FFFFFF',
      'on-background': '#1D1B20',
      'surface': '#FEF7FF',
      'on-surface': '#1D1B20',
      'surface-variant': '#E7E0EB',
      'on-surface-variant': '#49454E',
      'outline': '#7A757F',
      'outline-variant': '#CBC4CF',
      'shadow': '#000000',
      'scrim': '#000000',
      'inverse-surface': '#322F35',
      'inverse-on-surface': '#F5EFF7',
      'inverse-primary': '#D3BCFD',
      'primary-fixed': '#EBDDFF',
      'on-primary-fixed': '#230F46',
      'primary-fixed-dim': '#D3BCFD',
      'on-primary-fixed-variant': '#4F3D74',
      'secondary-fixed': '#E9DEF8',
      'on-secondary-fixed': '#1F182B',
      'secondary-fixed-dim': '#CDC2DB',
      'on-secondary-fixed-variant': '#4B4358',
      'tertiary-fixed': '#FFD9E1',
      'on-tertiary-fixed': '#31101B',
      'tertiary-fixed-dim': '#F0B7C5',
      'on-tertiary-fixed-variant': '#643B46',
      'surface-dim': '#DED8E0',
      'surface-bright': '#FEF7FF',
      'surface-container-lowest': '#FFFFFF',
      'surface-container-low': '#F8F1FA',
      'surface-container': '#F2ECF4',
      'surface-container-high': '#EDE6EE',
      'surface-container-highest': '#E7E0E8',
    }
  },
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/'
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
    }),
    presetTheme({
      theme: {
        dark: {
          'primary': '#D3BCFD',
          'success': '#22c55e',
          'warning': '#eab308',
          'surface-tint': '#D3BCFD',
          'on-primary': '#38265C',
          'primary-container': '#4F3D74',
          'on-primary-container': '#EBDDFF',
          'secondary': '#CDC2DB',
          'on-secondary': '#342D40',
          'secondary-container': '#4B4358',
          'on-secondary-container': '#E9DEF8',
          'tertiary': '#F0B7C5',
          'on-tertiary': '#4A2530',
          'tertiary-container': '#643B46',
          'on-tertiary-container': '#FFD9E1',
          'error': '#FFB4AB',
          'on-error': '#690005',
          'error-container': '#93000A',
          'on-error-container': '#FFDAD6',
          'background': '#151218',
          'on-background': '#E7E0E8',
          'surface': '#151218',
          'on-surface': '#E7E0E8',
          'surface-variant': '#49454E',
          'on-surface-variant': '#CBC4CF',
          'outline': '#948F99',
          'outline-variant': '#49454E',
          'shadow': '#000000',
          'scrim': '#000000',
          'inverse-surface': '#E7E0E8',
          'inverse-on-surface': '#322F35',
          'inverse-primary': '#68548E',
          'primary-fixed': '#EBDDFF',
          'on-primary-fixed': '#230F46',
          'primary-fixed-dim': '#D3BCFD',
          'on-primary-fixed-variant': '#4F3D74',
          'secondary-fixed': '#E9DEF8',
          'on-secondary-fixed': '#1F182B',
          'secondary-fixed-dim': '#CDC2DB',
          'on-secondary-fixed-variant': '#4B4358',
          'tertiary-fixed': '#FFD9E1',
          'on-tertiary-fixed': '#31101B',
          'tertiary-fixed-dim': '#F0B7C5',
          'on-tertiary-fixed-variant': '#643B46',
          'surface-dim': '#151218',
          'surface-bright': '#3B383E',
          'surface-container-lowest': '#0F0D13',
          'surface-container-low': '#1D1B20',
          'surface-container': '#211F24',
          'surface-container-high': '#2C292F',
          'surface-container-highest': '#36343A',
        },
      }
    }) as any
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
